baseURL: https://vuejstutorial.com
title: Vuejs Tutorial
theme: default

taxonomies:
  tag: tags

pygmentsUseClasses: true
pygmentsCodefences: true

googleAnalytics: "UA-34244433-5"

outputs:
  home: ["HTML", "JSON"]
